# This is a basic workflow to help you get started with Actions

name: UPDATE

on:
  workflow_dispatch
  #schedule:
    #- cron: '0 21 * * *'

jobs:
  build:
    runs-on: ubuntu-latest # 最新のubuntuで実行
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: "3.9"

      - name: Install pip
        run: | 
          python -m pip install --upgrade pip
          pip install requests lxml
          pip install Mako
          pip install tqdm
          pip install googletrans==4.0.0-rc1
          pip install selenium
    
      - name: Install geckodriver
        run: |
          sudo apt install firefox
          sudo apt install wget
          wget -O geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.29.1/geckodriver-v0.29.1-linux64.tar.gz
          tar -xvzf geckodriver
          chmod +x geckodriver
          sudo mv geckodriver /usr/local/bin/
          export  WEBDRIVER_EXE_PATH=/usr/local/bin/geckodriver

      - name: Run main.py # 未翻訳ファイルの翻訳
        run: |
          python main.py

      #TODO アップデートしたファイル名を確認
      - name: Commit and Push # 翻訳結果をpush
        run: |
          git config user.name "update"
          git config user.email "update@rfc-translater.com"
          git add .
          git commit -m "UPDATE `date +%Y%m%d_%H%M%S`"
          git pull
          git push origin master
          
